# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      # Runs a single command using the runners shell
      - name: Build
        run: echo "Build"

      - name: Teste
        run: echo "Teste"

      - name: Deploy
        run: echo "Deploy"
